name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 0: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 1: Pruebas de SAST
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      # Paso para verificar acceso a secretos (opcional para depuración)
      - name: Verificar acceso a secretos
        run: |
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "PASSWORD: ${{ secrets.PASSWORD }}"

      # Paso 2: Crear archivo de credenciales
      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini
        shell: bash

      # Paso 3: Construcción de Docker
      - name: Build docker image
        run: |
          docker build -t devops_ws:$(date +%s) .
        working-directory: ${{ github.workspace }}

      # Paso 4: Listar los archivos en el directorio de trabajo (para depuración)
      - name: List files in workspace
        run: ls -la
